# ==============================================================================
# SonarQube Project Configuration
# ==============================================================================

# Required: Your unique project identifier from SonarQube Cloud
sonar.projectKey=dhernandez-work_CDV1C02_Project2
sonar.organization=dhernandez-work

# Python Version & Directories
sonar.python.version=3.9
sonar.sources=src,app.py
sonar.tests=tests

# Tell SonarQube where the XML coverage report is located
sonar.python.coverage.reportPaths=reports/coverage.xml