# ==============================================================================
# SonarQube Project Configuration
# ==============================================================================

# ------------------------------------------------------------------------------
# Python Version
# Resolves: "get a more precise analysis by setting the Python version"
# Setting to 3.9 to match our Tech Stack defined in the README
# ------------------------------------------------------------------------------
sonar.python.version=3.9

# ------------------------------------------------------------------------------
# Source and Test Directories
# Resolves: "sonar.tests is not configured"
# ------------------------------------------------------------------------------
# Define where the main production code lives
sonar.sources=src,app.py

# Define where the unit tests live so SonarQube ignores them for production rules
sonar.tests=tests